### ISSUE TITLE
Where is Usage or Explanation? 

### ISSUE THREAD

**Issue by kazuman519** [mattak/CameraUploader#1]
I'm interested in this application.

**Comment by akihiro0228** [comment]
👍

**Comment by pine** [comment]
👍

**Comment by YutaKosuki** [comment]
👍

**Comment by mattak** [comment]
Sorry this application is no longer maintenanced.
Please refer great new camera application https://github.com/jwyjoy/sample_camera

Thanks 😄

**Comment by jwyjoy** [comment]
:+1:
